import type { RecognitionValidationCase } from "../types.js";

export const employerRecognitionCases: readonly RecognitionValidationCase[] = [
  {
    caseId: "same-loxam-business-units",
    observationIds: ["loxam-access-strasbourg", "loxam-rental-haguenau"],
    expectedRelationship: "SAME_EMPLOYER_CLUSTER",
    expectedConfidenceZone: "AUTO_MATCH",
    humanExplanation: "Both observations explicitly concern LOXAM, although the business unit and hiring location differ.",
    status: "VERIFIED",
  },
  {
    caseId: "same-altrad-endel-direct",
    observationIds: ["altrad-endel-maintenance", "altrad-endel-project"],
    expectedRelationship: "SAME_EMPLOYER_CLUSTER",
    expectedConfidenceZone: "AUTO_MATCH",
    humanExplanation: "Both sanitized excerpts explicitly identify ALTRAD ENDEL.",
    status: "VERIFIED",
  },
  {
    caseId: "possible-anonymous-wood-energy",
    observationIds: ["anonymous-wood-energy-adsearch", "anonymous-wood-energy-compatible"],
    expectedRelationship: "POSSIBLE_SAME_EMPLOYER",
    expectedConfidenceZone: "REVIEW_REQUIRED",
    humanExplanation: "The independent family ownership, scale, wood-and-energy activity, and Strasbourg-area geography are compatible but do not explicitly establish identity.",
    status: "NEEDS_REVIEW",
  },
  {
    caseId: "possible-anonymous-precision-machining",
    observationIds: ["anonymous-machining-teamis", "anonymous-machining-compatible"],
    expectedRelationship: "POSSIBLE_SAME_EMPLOYER",
    expectedConfidenceZone: "REVIEW_REQUIRED",
    humanExplanation: "Both anonymous observations share Wasselonne precision-machining, small-parts, turning/milling, CAD/CAM, and Siemens CNC clues.",
    status: "NEEDS_REVIEW",
  },
  {
    caseId: "different-actua-anonymous-clients",
    observationIds: ["actua-food-client", "actua-concrete-client"],
    expectedRelationship: "DIFFERENT_EMPLOYERS",
    expectedConfidenceZone: "NO_MATCH",
    humanExplanation: "The shared ACTUA intermediary and city do not overcome explicit food-versus-concrete client industries.",
    status: "VERIFIED",
  },
  {
    caseId: "different-same-area-contradictory-industries",
    observationIds: ["solina-france-production", "actua-concrete-client"],
    expectedRelationship: "DIFFERENT_EMPLOYERS",
    expectedConfidenceZone: "NO_MATCH",
    humanExplanation: "Similar production work around Weyersheim concerns incompatible food-solutions and concrete-manufacturing employers.",
    status: "VERIFIED",
  },
  {
    caseId: "different-explicit-solina-alstom",
    observationIds: ["solina-france-production", "alstom-transport-production"],
    expectedRelationship: "DIFFERENT_EMPLOYERS",
    expectedConfidenceZone: "NO_MATCH",
    humanExplanation: "SOLINA FRANCE and ALSTOM TRANSPORT SA are different explicitly named employers.",
    status: "VERIFIED",
  },
  {
    caseId: "insufficient-generic-maintenance",
    observationIds: ["generic-maintenance-north", "generic-maintenance-south"],
    expectedRelationship: "INSUFFICIENT_EVIDENCE",
    expectedConfidenceZone: "UNSCORED",
    humanExplanation: "Generic maintenance wording and broad geography provide too little employer-specific evidence for a human label.",
    status: "OPEN",
  },
  {
    caseId: "same-heuft-different-occupations",
    observationIds: ["heuft-commissioning", "heuft-support"],
    expectedRelationship: "SAME_EMPLOYER_CLUSTER",
    expectedConfidenceZone: "AUTO_MATCH",
    humanExplanation: "Both observations explicitly identify HEUFT France even though the occupations differ.",
    status: "VERIFIED",
  },
  {
    caseId: "same-blue-paper-cross-source",
    observationIds: ["blue-paper-hellowork", "blue-paper-employer-site"],
    expectedRelationship: "SAME_EMPLOYER_CLUSTER",
    expectedConfidenceZone: "AUTO_MATCH",
    humanExplanation: "Different source types explicitly identify the same Blue Paper employer and Strasbourg site.",
    status: "VERIFIED",
  },
  {
    caseId: "different-supplay-anonymous-clients",
    observationIds: ["supplay-logistics-client", "supplay-metal-client"],
    expectedRelationship: "DIFFERENT_EMPLOYERS",
    expectedConfidenceZone: "NO_MATCH",
    humanExplanation: "The same staffing intermediary publishes vacancies for distinct anonymous logistics and metal-processing clients in different locations.",
    status: "NEEDS_REVIEW",
  },
  {
    caseId: "possible-anonymous-robopac-packaging",
    observationIds: ["anonymous-robopac-a", "anonymous-robopac-b"],
    expectedRelationship: "POSSIBLE_SAME_EMPLOYER",
    expectedConfidenceZone: "REVIEW_REQUIRED",
    humanExplanation: "The shared Molsheim geography, ROBOPAC distributor fact, and end-of-line packaging product are highly distinctive without explicit employer identity.",
    status: "NEEDS_REVIEW",
  },
];
